include: package:very_good_analysis/analysis_options.6.0.0.yaml

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    prefer_single_quotes: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false
