name: fdawg
description: "Flutter Project Assistant"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  fdawg_namer:
    path: dawgs/fdawg_namer

  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  go_router: ^14.6.0
  hive: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/platforms/

  fonts:
    - family: Ubuntu Sans
      fonts:
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-LightItalic.ttf
          style: italic
          weight: 300

        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-Italic.ttf
          style: italic
          weight: 400

        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Ubuntu Sans/UbuntuSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
