# Jekyll configuration for GitHub Pages
title: FDAWG Documentation
description: Flutter Development Assistant with Go - Comprehensive CLI tool and web interface for Flutter project management
url: "https://jerinji2016.github.io"
baseurl: "/fdawg"

# Theme - Using just-the-docs for Flutter-like appearance
remote_theme: just-the-docs/just-the-docs
color_scheme: flutter
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Just the Docs theme configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_sort: case_insensitive
nav_external_links:
  - title: "GitHub Repository"
    url: "https://github.com/Jerinji2016/fdawg"
    hide_icon: false

# Footer content
footer_content: "Copyright &copy; 2024 FDAWG. Made with ❤️ for the Flutter community."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections
collections:
  commands:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      nav_order: 1
  - scope:
      path: ""
      type: "commands"
    values:
      layout: "default"
      parent: "Command Reference"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
