# Jekyll configuration for GitHub Pages
title: FDAWG Documentation
description: Flutter Development Assistant with Go - Comprehensive CLI tool and web interface for Flutter project management
url: "https://jerinji2016.github.io"
baseurl: "/fdawg"

# Custom theme - no remote theme dependency
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub metadata
repository: "Jerinji2016/fdawg"
github:
  repository_url: "https://github.com/Jerinji2016/fdawg"
  repository_name: "fdawg"
  owner_name: "Jerinji2016"

# Show downloads - changed to false, we'll add GitHub stars instead
show_downloads: false

# Enhanced navigation structure for left sidebar
navigation:
  - title: "Getting Started"
    icon: "🚀"
    items:
      - title: "Home"
        url: "/"
      - title: "Installation"
        url: "/installation/"
  - title: "User Interface"
    icon: "🖥️"
    items:
      - title: "Web Interface"
        url: "/web-interface/"
  - title: "Commands"
    icon: "⚡"
    items:
      - title: "Overview"
        url: "/commands/"
      - title: "Environment Management"
        url: "/commands/environment/"
        description: "Manage Flutter SDK versions and environments"
      - title: "Asset Management"
        url: "/commands/assets/"
        description: "Handle app icons, splash screens, and assets"
      - title: "Localization"
        url: "/commands/localization/"
        description: "Internationalization and localization tools"
      - title: "App Namer"
        url: "/commands/namer/"
        description: "Rename and rebrand Flutter applications"
      - title: "Bundler"
        url: "/commands/bundler/"
        description: "Refactor bundle id across all platforms"
      - title: "Development Server"
        url: "/commands/server/"
        description: "Local development server and hot reload"
  - title: "Development"
    icon: "🛠️"
    items:
      - title: "Contributing"
        url: "/development/"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections
collections:
  commands:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
