# Jekyll configuration for GitHub Pages
title: FDAWG Documentation
description: Flutter Development Assistant with Go - Comprehensive CLI tool and web interface for Flutter project management
url: "https://jerinji2016.github.io"
baseurl: "/fdawg"

# Custom theme - no remote theme dependency
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub metadata
repository: "Jerinji2016/fdawg"
github:
  repository_url: "https://github.com/Jerinji2016/fdawg"
  repository_name: "fdawg"
  owner_name: "Jerinji2016"

# Show downloads - changed to false, we'll add GitHub stars instead
show_downloads: false

# Navigation structure for midnight theme
navigation:
  - title: "Home"
    url: "/"
  - title: "Installation"
    url: "/installation.html"
  - title: "Web Interface"
    url: "/web-interface.html"
  - title: "Commands"
    url: "/commands/"
    subnav:
      - title: "Environment"
        url: "/commands/environment.html"
      - title: "Assets"
        url: "/commands/assets.html"
      - title: "Localization"
        url: "/commands/localization.html"
      - title: "App Namer"
        url: "/commands/namer.html"
      - title: "Server"
        url: "/commands/server.html"
  - title: "Development"
    url: "/development.html"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections
collections:
  commands:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
